export type CertificationHolder =
  | 'cms-group'
  | 'bath-n-room'
  | 'baba-muktinath'
  | '4r-technologies'
  | 'cubic-meter'
  | 'techwood'
  | 'prime-ceramics'
  | 'shree-swastik'
  | 'green-building-technologies'

export interface CertificationEntry {
  id: string
  brand: string
  type: string
  holder: string
  holderVenture?: CertificationHolder
  scope: string
  country?: string
  issued?: string
  validFrom?: string
  validUntil?: string
  scanImage?: string
}

export const CERTIFICATIONS: CertificationEntry[] = [
  {
    id: 'dormakaba',
    scanImage: '/images/certificates/dormakaba.jpg',
    brand: 'Dormakaba',
    type: 'Certified Project Partner',
    holder: 'CMS Group, Kathmandu',
    holderVenture: 'cms-group',
    scope: 'Authorised Project Partner of dormakaba India Private Limited',
    country: 'Germany',
    validFrom: '2023-04-01',
    validUntil: '2024-03-31',
  },
  {
    id: 'gunnebo',
    scanImage: '/images/certificates/gunnebo.jpg',
    brand: 'Gunnebo',
    type: 'Letter of Authorization',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Authorised distributor of Entrance Control & Perimeter Protection products for Nepal market',
    country: 'Sweden',
    issued: '2019-05-01',
    validUntil: '2020-05-01',
  },
  {
    id: 'lixil-tostem',
    scanImage: '/images/certificates/lixil-tostem.jpg',
    brand: 'LIXIL / Tostem',
    type: 'Letter of Authorization',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Authorised channel partner for sale & marketing of TOSTEM and TOSTEM ALU+ aluminium doors & windows',
    country: 'Japan',
    issued: '2021-04-12',
    validUntil: '2022-03-31',
  },
  {
    id: 'kalzip',
    scanImage: '/images/certificates/kalzip.jpg',
    brand: 'Kalzip',
    type: 'Letter of Authorization',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Authorised distributor of Kalzip Roofing and Façade Systems for Nepal market',
    country: 'Germany',
    issued: '2021-06-02',
    validUntil: '2022-06-02',
  },
  {
    id: 'navair',
    scanImage: '/images/certificates/navair.jpg',
    brand: 'Navair',
    type: 'Authorised Distributorship',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Steel Fire Doors, Stainless steel fire doors, Wooden fire doors, Fire-rated Glass doors, Steel Non-Fire rated HMPS Doors & Frames',
    country: 'India',
    issued: '2021-04-14',
    validFrom: '2021-04-01',
    validUntil: '2022-03-31',
  },
  {
    id: 'iko-armoroof',
    scanImage: '/images/certificates/iko.jpg',
    brand: 'IKO (Armoroof Export Division)',
    type: 'Authorized Distributorship Certificate',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Authorized distributor of IKO products for Nepal',
    country: 'Canada',
    issued: '2017-07-10',
  },
  {
    id: 'tostem-channel',
    scanImage: '/images/certificates/tostem.jpg',
    brand: 'Tostem',
    type: 'Authorised Channel Partner',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Authorised Channel Partner — Certificate No. 2022-046',
    country: 'Japan',
    validFrom: '2022-04-01',
    validUntil: '2023-03-31',
  },
  {
    id: 'knauf',
    scanImage: '/images/certificates/knauf.jpg',
    brand: 'Knauf Ceiling Solutions',
    type: 'Letter of Authority',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Non-exclusive channel partner authorised to resell KCS products and accessories in Nepal',
    country: 'Germany',
    issued: '2023-09-09',
    validFrom: '2023-01-01',
    validUntil: '2023-12-31',
  },
  {
    id: 'hunter-douglas',
    scanImage: '/images/certificates/hunter-douglas.jpg',
    brand: 'Hunter Douglas',
    type: 'Dealership Certificate',
    holder: 'Baba Muktinath Fabricators',
    holderVenture: 'baba-muktinath',
    scope: 'Authorized Dealer — Hunter Douglas India Pvt. Ltd. Architectural Division',
    country: 'Germany',
    validFrom: '2021-03-12',
    validUntil: '2022-03-11',
  },
  {
    id: 'duravit',
    scanImage: '/images/certificates/duravit.jpg',
    brand: 'Duravit',
    type: 'Authorised Partner',
    holder: 'Shree Swastik Traders',
    holderVenture: 'shree-swastik',
    scope: 'Authorised Partner for Duravit sanitaryware',
    country: 'Germany',
    validFrom: '2019-01-01',
    validUntil: '2020-12-31',
  },
  {
    id: 'ardex-endura',
    brand: 'Ardex Endura',
    type: 'Dealership Certificate',
    holder: 'CMS Group, Kathmandu',
    holderVenture: 'cms-group',
    scope: 'Authorised for sale & distribution of ARDEX ENDURA waterproofing and construction-chemical products',
    country: 'Germany–India',
    validUntil: '2023-12-31',
  },
  {
    id: 'somany',
    scanImage: '/images/certificates/somany.jpg',
    brand: 'Somany (Duragres Lounge)',
    type: 'Certificate of Association',
    holder: 'Shree Swastik Trader',
    holderVenture: 'shree-swastik',
    scope: 'Certified franchise of Somany Ceramics Ltd. — premium Duragres tiles store',
    country: 'India',
    validFrom: '2020-02-01',
    validUntil: '2021-03-31',
  },
  {
    id: 'bkb-hevea',
    scanImage: '/images/certificates/bkb.jpg',
    brand: 'BKB (Hevea Products)',
    type: 'Certificate of Authorization',
    holder: 'Cubic Meter Pvt. Ltd.',
    holderVenture: 'cubic-meter',
    scope: 'Sole Distributor of BKB 3-Ply Engineered Hardwood Flooring in Nepal — produced by B.K.B. Hevea Products Sdn. Bhd.',
    country: 'Malaysia',
    issued: '2021-03-26',
  },
  {
    id: 'sintex',
    scanImage: '/images/certificates/sintex.jpg',
    brand: 'Sintex',
    type: 'Letter of Distribution',
    holder: 'Green Building Technologies',
    holderVenture: 'green-building-technologies',
    scope: 'Local partner for Nepal sales since 2015 — sewage treatment plants, fuel storage tanks, water storage tanks (1,200 to 1,50,000 ltrs)',
    country: 'India',
    issued: '2021-03-19',
  },
  {
    id: 'sos-spacewood',
    scanImage: '/images/certificates/sos-spacewood.jpg',
    brand: 'SOS / Spacewood',
    type: 'Dealer Certificate',
    holder: 'Tech Wood Pvt. Ltd., Pulchowk-10, Lalitpur',
    holderVenture: 'techwood',
    scope: 'Authorised to Sell & Service products of Spacewood Office Solutions Pvt. Ltd.',
    country: 'India',
    issued: '2019-01-01',
    validUntil: '2020-03-31',
  },
  {
    id: 'kingspan-shubham',
    scanImage: '/images/certificates/kingspan-rhino.jpg',
    brand: 'Kingspan Rhino (Shubham Tanks)',
    type: 'Authorized Letter',
    holder: 'Green Building Technologies',
    holderVenture: 'green-building-technologies',
    scope: 'Authorised business partner for Shubham Tanks & Liners — manufacturers of Kingspan Rhino water-storage solutions',
    country: 'Australia / India',
    issued: '2022-11-01',
    validUntil: '2024-03-31',
  },
  {
    id: 'oase',
    scanImage: '/images/certificates/oase.jpg',
    brand: 'Oase',
    type: 'Authorised Distributor',
    holder: 'Green Building Technologies',
    holderVenture: 'green-building-technologies',
    scope: 'Right to sell and distribute OASE products in Nepal',
    country: 'Germany',
    issued: '2019-11-05',
  },
  {
    id: 'welspun',
    scanImage: '/images/certificates/welspun.jpg',
    brand: 'Welspun Flooring',
    type: 'Authorised Channel Partner',
    holder: 'Techwood (CMS Group)',
    holderVenture: 'techwood',
    scope: 'Authorised Channel Partner for Welspun Flooring',
    country: 'India',
    validUntil: '2023-03-31',
  },
]
